### ISSUE TITLE
Using MapTo

### ISSUE THREAD

**Issue by gr0undzer0** [go-ini/ini#41]
I'm pretty sure this isn't the right place to be asking for help but I'm not sure who else the experts would be :) 

I'm tying to map cfg to a struct called Config in the code below. I do this but when I go to print conf it always shows up with empty and false values. 

```
type Config struct {
    host string
    port int
}

func main () {
    cfg, err := ini.Load("/my/file.cfg")
    conf := new(Config)
    err = cfg.MapTo(conf)
    fmt.Println(conf)
```

When I run this I get 
&{ 0}

If I use: cfg.Section("").Key("host")
I can get access to the Value for "host"

Am I trying to use MapTo incorrectly?

**Comment by silasray** [comment]
You probably figured it out already, but you need to start field names with upper case in the struct so that they can be assigned to by the parser (aka they need to be public).  In order to make that work without changing the names in the ini file though, you need to use the TitleUnderscore NameMapper by assigning it to the ini object or passing it in and using MapToWithMapper.

**Comment by Unknwon** [comment]
@silasray has posted the solution...
